version: '3'

services:
  django:
    build: 
      context: .
      dockerfile: Dockerfile
    command: /code/docker-entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    stdin_open: True
    tty: True