# Generated by Django 2.1.5 on 2019-03-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CallsRegisters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('country', models.CharField(max_length=250)),
                ('year', models.CharField(max_length=4)),
            ],
        ),
    ]
