# Generated by Django 2.1.5 on 2019-03-02 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CallsRegisters', '0002_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='year',
            name='countries',
        ),
        migrations.AlterModelOptions(
            name='aidmonetary',
            options={'ordering': ('year', 'budget')},
        ),
        migrations.AddField(
            model_name='aidmonetary',
            name='country',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='aids', to='CallsRegisters.Country'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aidmonetary',
            name='year',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='Year',
        ),
    ]
