# Generated by Django 2.1.5 on 2019-03-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CallsRegisters', '0003_auto_20190302_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(max_length=50),
        ),
    ]
